#!/usr/bin/env bash
# Regenerates components/icons.tsx from the Aria Icons HTTP API.
#
# Source:  https://icons.leularia.com  (GET /api/v1/icon?id=<collection:name>)
# We call the API directly with curl instead of running the `aria-icons` npm
# CLI, because this repo's security policy (docs/security.md) forbids running
# npm/node on the host. The API response is treated as data only: we extract
# the SVG child elements and attributes with a strict allow-list.
#
# License: all icons are from the Lucide collection (https://lucide.dev),
# licensed under the ISC License:
#   Copyright (c) for portions of Lucide are held by Cole Bemis 2013-2022 as
#   part of Feather (MIT). All other copyright (c) for Lucide are held by
#   Lucide Contributors 2022. Permission to use, copy, modify, and/or
#   distribute this software for any purpose with or without fee is hereby
#   granted, provided that the above copyright notice and this permission
#   notice appear in all copies.
#
# To add an icon: append its id (lucide:<name>) to ICONS below, run
#   bash frontend/scripts/fetch-icons.sh
# and commit the regenerated components/icons.tsx. If an id 404s, try
#   GET /api/v1/search?q=<name>&collection=lucide&limit=3
# and use the closest match.
#
# Substitutions (Lucide renamed these icons):
#   message-circle-question -> message-circle-question-mark
#   alert-triangle          -> triangle-alert
set -euo pipefail

ICONS=(
  lucide:book-open
  lucide:library
  lucide:search
  lucide:sliders-horizontal
  lucide:arrow-up-down
  lucide:chevron-left
  lucide:chevron-right
  lucide:chevron-down
  lucide:settings
  lucide:log-in
  lucide:log-out
  lucide:user
  lucide:key-round
  lucide:external-link
  lucide:upload
  lucide:link
  lucide:file-text
  lucide:languages
  lucide:sparkles
  lucide:message-circle-question-mark
  lucide:flag
  lucide:check
  lucide:lock
  lucide:lock-open
  lucide:pencil
  lucide:bookmark
  lucide:bookmark-check
  lucide:list
  lucide:x
  lucide:loader-circle
  lucide:sun
  lucide:moon
  lucide:type
  lucide:triangle-alert
)

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT="$HERE/../components/icons.tsx"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

for id in "${ICONS[@]}"; do
  curl -fsS --max-time 30 "https://icons.leularia.com/api/v1/icon?id=${id}" -o "$TMP/${id//:/__}.json"
done

python3 - "$TMP" "$OUT" "${ICONS[@]}" <<'PY'
import json, re, sys

tmp, out, *ids = sys.argv[1:]
ALLOWED = {"path", "circle", "rect", "line", "polyline", "polygon", "ellipse"}
ATTR = re.compile(r'([a-zA-Z][\w:-]*)\s*=\s*"([^"]*)"')

def camel(name):
    parts = name.split("-")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])

def pascal(name):
    return "".join(p[:1].upper() + p[1:] for p in re.split(r"[-_]", name))

lines = [
    "// GENERATED by frontend/scripts/fetch-icons.sh. Do not edit by hand.",
    "// Icons: Lucide (ISC License), fetched via the Aria Icons API (https://icons.leularia.com).",
    "// Copyright (c) Cole Bemis 2013-2022 (Feather, MIT) and Lucide Contributors 2022.",
    "import type { ReactNode, SVGProps } from \"react\";",
    "",
    "export type IconProps = Omit<SVGProps<SVGSVGElement>, \"title\"> & {",
    "  size?: number;",
    "  title?: string;",
    "};",
    "",
    "function Svg({ size = 18, title, children, ...rest }: IconProps & { children: ReactNode }) {",
    "  const a11y = title",
    "    ? { role: \"img\" as const }",
    "    : { \"aria-hidden\": true as const, focusable: \"false\" as const };",
    "  return (",
    "    <svg",
    "      xmlns=\"http://www.w3.org/2000/svg\"",
    "      width={size}",
    "      height={size}",
    "      viewBox=\"0 0 24 24\"",
    "      fill=\"none\"",
    "      stroke=\"currentColor\"",
    "      strokeWidth={2}",
    "      strokeLinecap=\"round\"",
    "      strokeLinejoin=\"round\"",
    "      {...a11y}",
    "      {...rest}",
    "      className={rest.className ? `icon ${rest.className}` : \"icon\"}",
    "    >",
    "      {title ? <title>{title}</title> : null}",
    "      {children}",
    "    </svg>",
    "  );",
    "}",
]

for id in ids:
    data = json.load(open(f"{tmp}/{id.replace(':', '__')}.json"))
    svg = data["svg"]
    root = re.match(r"<svg\b([^>]*)>", svg, re.S)
    rattrs = dict(ATTR.findall(root.group(1)))
    expect = {"viewBox": "0 0 24 24", "fill": "none", "stroke": "currentColor",
              "stroke-width": "2", "stroke-linecap": "round", "stroke-linejoin": "round"}
    for k, v in expect.items():
        if rattrs.get(k) != v:
            sys.exit(f"{id}: unexpected root attribute {k}={rattrs.get(k)!r}")
    children = []
    for m in re.finditer(r"<([a-zA-Z]+)\b([^>]*?)/?>", svg[root.end():]):
        tag = m.group(1)
        if tag == "svg" or m.group(0).startswith("</"):
            continue
        if tag not in ALLOWED:
            sys.exit(f"{id}: unsupported element <{tag}>")
        attrs = " ".join(f'{camel(k)}="{v}"' for k, v in ATTR.findall(m.group(2)))
        children.append(f"      <{tag} {attrs} />")
    name = "Icon" + pascal(id.split(":", 1)[1])
    lines += ["", f"export function {name}(props: IconProps) {{", "  return (", "    <Svg {...props}>"]
    lines += children
    lines += ["    </Svg>", "  );", "}"]

open(out, "w").write("\n".join(lines) + "\n")
PY
echo "wrote $OUT (${#ICONS[@]} icons)"
